from ..quantities import output as q
from ..quantities import nanoAOD as nanoAOD
from code_generation.producer import ExtendedVectorProducer

####################
# Set of producers used for trigger flags
####################

MMGenerateSingleMuonTriggerFlags = ExtendedVectorProducer(
    name="MMGenerateSingleMuonTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["mm"],
    vec_config="singlemoun_trigger",
)
MTGenerateSingleMuonTriggerFlags = ExtendedVectorProducer(
    name="MTGenerateSingleMuonTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, 
        {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["mt"],
    vec_config="singlemoun_trigger",
)
ETGenerateSingleElectronTriggerFlags = ExtendedVectorProducer(
    name="ETGenerateSingleElectronTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, 
        {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["et"],
    vec_config="singleelectron_trigger",
)
EMGenerateSingleElectronTriggerFlags = ExtendedVectorProducer(
    name="EMGenerateSingleElectronTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, 
        {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["em"],
    vec_config="singleelectron_trigger",
)
GenerateSingleLeadingTauTriggerFlags = ExtendedVectorProducer(
    name="GenerateSingleLeadingTauTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, 
        {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["tt"],
    vec_config="singletau_trigger_leading",
)
GenerateSingleTrailingTauTriggerFlags = ExtendedVectorProducer(
    name="GenerateSingleTrailingTauTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, 
        {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_2,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["et", "mt", "tt"],
    vec_config="singletau_trigger_trailing",
)
EMGenerateSingleMuonTriggerFlags = ExtendedVectorProducer(
    name="EMGenerateSingleMuonTriggerFlags",
    call="""trigger::SingleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {ptcut}, 
        {etacut}, 
        {trigger_particle_id}, 
        {filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_2,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["em"],
    vec_config="singlemoun_trigger",
)
MTGenerateCrossTriggerFlags = ExtendedVectorProducer(
    name="GenerateCrossTriggerFlags",
    call="""trigger::DoubleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {p1_ptcut}, 
        {p2_ptcut}, 
        {p1_etacut}, 
        {p2_etacut}, 
        {p1_trigger_particle_id}, 
        {p2_trigger_particle_id}, 
        {p1_filterbit}, 
        {p2_filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        q.p4_2,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["mt"],
    vec_config="mutau_cross_trigger",
)
ETGenerateCrossTriggerFlags = ExtendedVectorProducer(
    name="GenerateCrossTriggerFlags",
    call="""trigger::DoubleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {p1_ptcut}, 
        {p2_ptcut}, 
        {p1_etacut}, 
        {p2_etacut}, 
        {p1_trigger_particle_id}, 
        {p2_trigger_particle_id}, 
        {p1_filterbit}, 
        {p2_filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        q.p4_2,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["et"],
    vec_config="eltau_cross_trigger",
)
TTGenerateDoubleTriggerFlags = ExtendedVectorProducer(
    name="TTGenerateDoubleTriggerFlags",
    call="""trigger::DoubleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {p1_ptcut}, 
        {p2_ptcut}, 
        {p1_etacut}, 
        {p2_etacut}, 
        {p1_trigger_particle_id}, 
        {p2_trigger_particle_id}, 
        {p1_filterbit}, 
        {p2_filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        q.p4_2,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["tt"],
    vec_config="doubletau_trigger",
)
EMGenerateCrossTriggerFlags = ExtendedVectorProducer(
    name="EMGenerateCrossTriggerFlags",
    call="""trigger::DoubleObjectFlag(
        {df}, 
        {output}, 
        {input}, 
        "{hlt_path}", 
        {p1_ptcut}, 
        {p2_ptcut}, 
        {p1_etacut}, 
        {p2_etacut}, 
        {p1_trigger_particle_id}, 
        {p2_trigger_particle_id}, 
        {p1_filterbit}, 
        {p2_filterbit}, 
        {max_deltaR_triggermatch})
        """,
    input=[
        q.p4_1,
        q.p4_2,
        nanoAOD.TrigObj_pt,
        nanoAOD.TrigObj_eta,
        nanoAOD.TrigObj_phi,
        nanoAOD.TrigObj_id,
        nanoAOD.TrigObj_filterBits,
    ],
    output="flagname",
    scope=["em"],
    vec_config="elmu_cross_trigger",
)
