# CI step to build the unittest container to be used for the other CI steps
# publish the container in the github container registry

name: Checks

# This workflow should only run when the Dockerfile changes
on:
  push:
    paths:
      - docker/Dockerfile
  pull_request:
    paths:
      - docker/Dockerfile
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-crown-unittest

jobs:
    build_unittest_container:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        - name: Build and push Docker image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
            context: .
            file: docker/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}