name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Settings go here!
env:
  ENV_NAME: env
  BUILD_TYPE: Release
  ANALYSIS: unittest
  CONFIG: unittest_config
  SAMPLES: dyjets
  ERAS: 2018
  SCOPES: "mt,mm,et"
  SHIFTS: "all"
  SINGLE_FRIEND_SCOPES: "mt,mm"
  SINGLE_FRIEND_CONFIG: unittest_friends
  TWO_FRIENDS_SCOPES: "mt"
  TWO_FRIENDS_CONFIG: unittest_friends_2
  FRIEND_SHIFTS: "nominal,jesUncTotalUp,jesUncTotalDown,tauMuFakeEsDown"

# This ensures every step runs in a login shell, automatically activating conda
defaults:
  run:
    shell: bash -el {0}

jobs:
  build_project:
    runs-on: ubuntu-24.04
    container:
      image: tvoigtlaender/kingmaker_standalone:V1.4j
      options: --user 0 # run as root

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.CERN_GITLAB_PRIVATE_KEY }}
          submodules: "recursive"
          ssh-strict: "false"
          ssh-known-hosts: "[gitlab.cern.ch]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubVS0czgKaPkC5cfB75CI3XjgWBv7pj2ILiZezVf8okkCAYr+bf4w6VrH2pyv3NRUW5Mm8U/3zoSNcrYIqhFFpz6R62/3xt8hMrPKJKstbt1lSIr8QhEyD24SJEKugMi560BWRPkTzXrrFgxz0X4vuKKytpvihRsccZ7F1JaX76UCWEJ3Xr2BFCEnnN6gj9nvFr4gvSMneunWVLGw2KcHwS1OJfnWBlp3fB0rYWSxZAoVjcjZjvv3hioEftaTapff2PkdQIX//N9Cc555FzdmMzixTvU5j/i+QvjxWVbEBNSKI6te6udC4fYUZMePs2QQnqw9mXUQtaQtw+HV7utuw=="

      - name: Mark git directory as safe
        run: git config --global --add safe.directory ${{github.workspace}}

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: adding a system path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          cd ${{github.workspace}}/build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DANALYSIS=$ANALYSIS -DCONFIG=$CONFIG -DSAMPLES=$SAMPLES -DERAS=$ERAS -DSCOPES=$SCOPES -DSHIFTS=$SHIFTS -DOPTIMIZED=false

      - name: Build
        run: |
          cd ${{github.workspace}}/build
          make install -j 2

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest -V --label-regex "ntuple.*."

  build_single_friend:
    runs-on: ubuntu-24.04
    container:
      image: tvoigtlaender/kingmaker_standalone:V1.4j
      options: --user 0 # run as root

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.CERN_GITLAB_PRIVATE_KEY }}
          submodules: "recursive"
          ssh-strict: "false"
          ssh-known-hosts: "[gitlab.cern.ch]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubVS0czgKaPkC5cfB75CI3XjgWBv7pj2ILiZezVf8okkCAYr+bf4w6VrH2pyv3NRUW5Mm8U/3zoSNcrYIqhFFpz6R62/3xt8hMrPKJKstbt1lSIr8QhEyD24SJEKugMi560BWRPkTzXrrFgxz0X4vuKKytpvihRsccZ7F1JaX76UCWEJ3Xr2BFCEnnN6gj9nvFr4gvSMneunWVLGw2KcHwS1OJfnWBlp3fB0rYWSxZAoVjcjZjvv3hioEftaTapff2PkdQIX//N9Cc555FzdmMzixTvU5j/i+QvjxWVbEBNSKI6te6udC4fYUZMePs2QQnqw9mXUQtaQtw+HV7utuw=="

      - name: Mark git directory as safe
        run: git config --global --add safe.directory ${{github.workspace}}

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: adding a system path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          cd ${{github.workspace}}/build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DANALYSIS=$ANALYSIS -DCONFIG=$SINGLE_FRIEND_CONFIG -DSAMPLES=$SAMPLES -DERAS=$ERAS -DSCOPES=$SINGLE_FRIEND_SCOPES -DSHIFTS=$FRIEND_SHIFTS -DOPTIMIZED=false -DQUANTITIESMAP="dummy"

      - name: Build
        run: |
          cd ${{github.workspace}}/build
          make install -j 2

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest -V --label-regex "single_friend.*."

  build_two_friends:
    runs-on: ubuntu-24.04
    container:
      image: tvoigtlaender/kingmaker_standalone:V1.4j
      options: --user 0 # run as root

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.CERN_GITLAB_PRIVATE_KEY }}
          submodules: "recursive"
          ssh-strict: "false"
          ssh-known-hosts: "[gitlab.cern.ch]:7999 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubVS0czgKaPkC5cfB75CI3XjgWBv7pj2ILiZezVf8okkCAYr+bf4w6VrH2pyv3NRUW5Mm8U/3zoSNcrYIqhFFpz6R62/3xt8hMrPKJKstbt1lSIr8QhEyD24SJEKugMi560BWRPkTzXrrFgxz0X4vuKKytpvihRsccZ7F1JaX76UCWEJ3Xr2BFCEnnN6gj9nvFr4gvSMneunWVLGw2KcHwS1OJfnWBlp3fB0rYWSxZAoVjcjZjvv3hioEftaTapff2PkdQIX//N9Cc555FzdmMzixTvU5j/i+QvjxWVbEBNSKI6te6udC4fYUZMePs2QQnqw9mXUQtaQtw+HV7utuw=="

      - name: Mark git directory as safe
        run: git config --global --add safe.directory ${{github.workspace}}

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: adding a system path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          cd ${{github.workspace}}/build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DANALYSIS=$ANALYSIS -DCONFIG=$TWO_FRIENDS_CONFIG -DSAMPLES=$SAMPLES -DERAS=$ERAS -DSCOPES=$TWO_FRIENDS_SCOPES -DSHIFTS=$FRIEND_SHIFTS -DOPTIMIZED=false -DQUANTITIESMAP="dummy"

      - name: Build
        run: |
          cd ${{github.workspace}}/build
          make install -j 2

      - name: Test
        run: |
          cd ${{github.workspace}}/build
          ctest -V --label-regex "two_friends.*."

  code_formatting:
    runs-on: ubuntu-24.04
    container:
      image: tvoigtlaender/kingmaker_standalone:V1.4j
      options: --user 0
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Mark git directory as safe
        run: git config --global --add safe.directory ${{github.workspace}}

      - name: Run all formatting checks
        run: bash ./checks/run-all-checks.sh

  docs:
    runs-on: ubuntu-24.04
    container:
      image: tvoigtlaender/kingmaker_standalone:V1.4j
      options: --user 0
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: |
          cd ${{github.workspace}}/build
          cmake $GITHUB_WORKSPACE/docs

      - name: Build docs
        run: |
          cd ${{github.workspace}}/build
          make

      - name: Publish
        run: echo "TODO"