name: Check formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-20.04
    container: rootproject/root:6.24.00-conda

    steps:
    - uses: actions/checkout@v2

    - name: Install missing software
      run: pip install black

    - name: Check Python formatting
      shell: bash
      run: cd ${{github.workspace}} && bash checks/python-formatting.sh
